db_name     = "strapi_db"
db_username = "strapi_user"
db_password = "strapi-pass"
app_keys    = "SrGRSHbSbHV/OUmId7doZg==,cL+QLmuRM9a9qlEl/adnyQ==,kp6YXYbOkeIqmu0YyevJTg==,XShDrs9TJTconCAJjL4SBw=="
api_token_salt = "DyBgHklIZdboUlQAZZ/42g=="
admin_jwt_secret = "BAtS+/RTXz97ztKthDHJ2g=="
transfer_token_salt = "kDiBX+hOa+bhAKPpSFR37A=="
encryption_key  = "8sPv6kraSJAPrV50wj2jpA=="
admin_auth_secret = "H3F9oWqv7J2u1PcQ5tUyZg=="
 